### ISSUE TITLE
Graphql support

### ISSUE THREAD

**Issue by vuki656** [vuki656/nvim-config#9]
Possible solution here: https://github.com/felippepuhle/coc-graphql/issues/6

**Comment by felippepuhle** [comment]
I'd use the [LSP config directly on CoC](https://github.com/neoclide/coc.nvim/wiki/Language-servers\#graphql). 

`coc-graphql` is just a wrapper to the LSP and it's out of date. I don't have time or any reason to keep updating it as we can use the configuration as suggested.

Thanks!

**Comment by vuki656** [comment]
> I'd use the [LSP config directly on CoC](https://github.com/neoclide/coc.nvim/wiki/Language-servers\#graphql). 
> 
> `coc-graphql` is just a wrapper to the LSP and it's out of date. I don't have time or any reason to keep updating it as we can use the configuration as suggested.
> 
> Thanks!

Will check it out. Thanks for the reply 😊
